### ISSUE TITLE
some issues with Transmock for bts2016

### ISSUE THREAD

**Issue by derkschutte** [svetvasilev/transmock#3] opened 2017-08-29 12:45 UTC
LS,

Love your work! I've been trying to get Transmock to work on a recently installed BizTalk 2016 server. I ran into a few issues:

- using the nuget off the shelve didn't work, as it forces a net 4.6.2 compiled version of BizUnit 5.0.5 that would not compile with our net 4.6 version BizTalk projects. 

- running install.ps1 it tries to load Microsoft.Servicemodel.Channels version 3.0.0.0. The version that ships with the prerequisite 2016 LOB Adapter SDK is 3.5.0.0. Perhaps this would work on an upgraded server but not a clean install, it just miises that assembly. For our local use i recompiled the TransMock.Wcf.Adapter assembly with a reference to the 3.5 version of Microsoft.Servicemodel.Channels, it then seems to run fine.

- the install.ps1 powershell assumes it is being run in 32 bit mode. If you run it in 64 bit mode the determination of the 32-bit/64-bit machine.config path does not work correctly. By default the 64 bit version is run.

- when trying to modify the 64-bit machine.config, the install.ps1 doesn't  seem to find the "client" section. This probably has nothing to do with transmock but maybe you have run into it too.

regards,
derk schutte

**Comment by svetvasilev** [comment] 2017-08-29 14:01
Thanks for your feedback Derk! Very valuable as I have definitely some limited setup to test the installation on, hence very dependent on pingbacks from the community like yours.
I presume that you managed to get it going so far, but i will definitely have a look at those issues and come with a fix. 
Couple of things though:
- i noticed that a warning comes about the target .net runtime when one compiles the test project referencing BizUnit 5.0.5. However i was able to run the tests without any issues locally. Could you please specify what is the exact error you are getting?
- install.ps1 runs by default in 32-bit mode if executed from within VS. Are you using a 64-bit version of VS? I would be surprised if you do as there is no such thing...at least not for version 2015...that i am aware of. If you run the script from PS prompt, then try to run it from the 32-version of it, or even better from within the Package manager console in VS.
- about the client section in 64-bit machine.config- was that after you tried to install the package through NPM and it failed? I experienced similar behavior during testing that this error would occur if installing the package after an unsuccessful prior installation. I would suggest that you inspect the machine.config file and see whether there were some remains from the previous installation that were not removed.
Cheers, Svet

**Comment by derkschutte** [comment] 2017-08-29 18:55
Svet,

-I am afraid I haven't kept the error text. But I think you should notice that the 4.6 binaries for BizUnit are 4.6.2. And that wouldn't compile referenced from my other 4.6 projects. As soon as I referenced the 4.0, it was okay.

-I haven't run it in Visual Studio. Due to the way things were set up at my customer's, it needed the old program files (86)\Transmock folder to be there, so I recreated that with newer assemblies and tried running it there in a powershell console.

-okay, guess that's not a big problem then, it did happen during several retries, so that would explain it.


If I understand correctly it (the install.ps1) is not adding an actual adapter, but only registering classes in the machine.config so that those bindings can be used, right?


regards

derk

________________________________
Van: svetvasilev <notifications@github.com>
Verzonden: dinsdag 29 augustus 2017 16:01:06
Aan: svetvasilev/transmock
CC: Derk Schutte; Author
Onderwerp: Re: [svetvasilev/transmock] some issues with Transmock for bts2016 (#3)


Thanks for your feedback Derk! Very valuable as I have definitely some limited setup to test the installation on, hence very dependent on pingbacks from the community like yours.
I presume that you managed to get it going so far, but i will definitely have a look at those issues and come with a fix.
Couple of things though:

  *   i noticed that a warning comes about the target .net runtime when one compiles the test project referencing BizUnit 5.0.5. However i was able to run the tests without any issues locally. Could you please specify what is the exact error you are getting?
  *   install.ps1 runs by default in 32-bit mode if executed from within VS. Are you using a 64-bit version of VS? I would be surprised if you do as there is no such thing...at least not for version 2015...that i am aware of. If you run the script from PS prompt, then try to run it from the 32-version of it, or even better from within the Package manager console in VS.
  *   about the client section in 64-bit machine.config- was that after you tried to install the package through NPM and it failed? I experienced similar behavior during testing that this error would occur if installing the package after an unsuccessful prior installation. I would suggest that you inspect the machine.config file and see whether there were some remains from the previous installation that were not removed.
Cheers, Svet

**Comment by svetvasilev** [comment] 2017-08-30 12:46
Hi Derk, 
I am looking at the issues you have mentioned. For now i only see that the real issue here is the wrong assembly versions to the Microsoft.ServiceModel.Channels assembly. Thanks for pointing that out. An update would soon be released with the correct references for each supported BizTalk version. 

- Yes, i noticed that the BizUnit 5.0.5 assemblies are targeting .net 4.6.2, yet I did not take any additional measures as, already mentioned, the only thing that I observed was during compile a warning about that was fired. However, upon executing the tests everything worked just fine. I can also confirm that the project is set to compile for .net v4.6. It may well be one of those "it works on my machine only" kind of things, but will first try to reproduce the behavior locally before I take any further steps.

- I would strongly recommend that you stick to the supported way of adding NUget packages to VS projects/solutions. The whole point of this update to TransMock was to solve one long standing issue with the framework -  namely to cut the requirement for it being deployed on the build server separately. Now you add the package to your projects and off you go - the assemblies, as well as the custom BTDF targets are part of the source control tree. Which means that when attempted built on the build server, it should just work fine without any additional support. Now even referencing the TransMock.targets file is done from within the packages folder - hence no more TransMock root folder reference hustle. Long live relative project paths! So I guess you have a much better excuse to recreate the TransMock path structure as per the older installers.

- The install.ps1 script is invoked as part of the NUget package install in order to register the adapter as a new WCF binding. This is sufficient for it to appear as a valid BizTalk binding when one is configuring the WCF-Custom adapter. So in reality you shouldn't be bothering executing this one manually. But i see that you needed to in your very peculiar setup.

**Comment by derkschutte** [comment] 2017-09-12 07:42
Svet,

tnx.


ad 1. Strange. I don't scare away from a few warnings but indeed on my machine it didn't build. I didn't have time to study why.

ad 2. Agreed, except that i am converting old Bts2010 to 2016 for my current customer and have to deal with how things are set up. In a next step if i get the change i will conform to the preferred way of using it.

ad 3. See 2 😊


Regards

derk

________________________________
Van: svetvasilev <notifications@github.com>
Verzonden: dinsdag 5 september 2017 10:27:39
Aan: svetvasilev/transmock
CC: Derk Schutte; Author
Onderwerp: Re: [svetvasilev/transmock] some issues with Transmock for bts2016 (#3)


Closed #3<https://github.com/svetvasilev/transmock/issues/3> via b873aec<https://github.com/svetvasilev/transmock/commit/b873aecc2a9cad8bde77727e3720b4713db8e41a>.

**Comment by svetvasilev** [comment] 2018-05-15 19:01
Seems that the issue with the wrong assembly reference version was not really fixed after all. Strange enough VS showed the correct assembly version in the properties tab when the Microsoft.ServiceModel.Channels reference was selected. However upon closer inspection of the csproj file the reference was still pointing to version 3.0.0.0 instead of 3.5.0.0.

**Comment by svetvasilev** [comment] 2018-05-22 07:17
Issue still not solved. Despite fixing the references the nuget package still contains a different version in the lib\net46 folder than intended as the reference is to the 3.0 and not 3.5 version.

**Closed as completed** 2018-05-23 06:31 UTC

**Comment by svetvasilev** [comment] 2018-05-23 06:36
The issue was related to the way VisualStudio builds projects from the IDE and how MSBuild handles references projects when building the nuproj projects. There was added a pre-build script that simply deletes the contents of the obj folder in order to avoid any stale files which result in ending up with an assembly built for different .NET target even if copied to the correct output folder. This fix however leads to the IDE failing to build the solution or any of the Nuget packages as it deadlocks on some of the files in the obj folder. It should therefore always be built by the bat scripts provided.
